version: '3.8'

services:
  # PostgreSQL - Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: fipe-postgres
    environment:
      POSTGRES_DB: fipe_db
      POSTGRES_USER: fipe_user
      POSTGRES_PASSWORD: fipe123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ - Sistema de Filas
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fipe-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"   # Porta para conexão da aplicação
      - "15672:15672" # Porta para interface web (http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: